name: Scheduled Slack Message

on:
  schedule:
    - cron: '0 15 * * *'  # UTC 時區，1點 = 台灣9點
  workflow_dispatch:      # 可以手動觸發

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"早安！這是自動化訊息。"}' \
            $SLACK_WEBHOOK_URL
