name: Leave Work

on:
  schedule:
    - cron: '45 10 * * 1-5'  # 台灣時間 18:45

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"<!here> \n::feet: 熊貓餓了，要回家吃飯了 喵喵～～"}' \
            $SLACK_WEBHOOK_URL
