name: Lunch Time

on:
  schedule:
    - cron: '0 4 * * 1-5'  # 台灣時間 12:00
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":":bento: 放飯啦，熊貓跟猴子要一起去吃飯了！！"}' \
            $SLACK_WEBHOOK_URL
