name: Take Dietary Supplements

on:
  schedule:
    - cron: '5 6 * * 1-5'  # 台灣時間 14:05

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"<!here> \n:pill: 請各位熊貓們拿起保健食品，咖噴咖 :panda_face:"}' \
            $SLACK_WEBHOOK_URL
