name: Test

on:
  schedule:
    - cron: '0 12 * * 1-5'  # 台灣時間 20:00
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"@here\n咖咖，熊貓測試熊貓測試 :panda_face::panda_face:"}' \
            $SLACK_WEBHOOK_URL
